version: '3.3'
services:
  budgets-postgres:
    image: postgres
    restart: always
    container_name: budgets-postgres
    volumes:
      - budgets-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=budgets
      - POSTGRES_DB=budgets
      - POSTGRES_USER=budgets
    ports:
      - 5432:5432

  budgets-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: budgets-server
    ports:
      - 3333:3333
    volumes:
      - ./packages/server:/workspace
    environment: 
      - PORT=3333
    depends_on: 
      - budgets-postgres

volumes:
  budgets-db:
