version: '3.3'
services:
  budgets-postgres:
    image: postgres
    restart: always
    container_name: budgets-postgres
    environment:
      - POSTGRES_PASSWORD=budgets
      - POSTGRES_DB=budgets
      - POSTGRES_USER=budgets
    ports:
      - 5432:5432