version: '3.3'

services:
    db:
        image: postgres
        restart: always
        volumes:
            - ./tmp/pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=budgets
        ports:
            - 5432:5432
    
    admin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=anhtoan@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=123
        ports:
            - 7000:80
