name: Buid CI

on:
  push:
    branches: [main]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies and build 
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Copy build to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: /home/$SSH_USER/www/ledger
          rmRemote: true
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
