name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_integration_test:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: budgets
          POSTGRES_USER: budgets
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Dependencies installation
        run: |
          npm install
          npm run bootstrap
      
      - name: Start back-end server
        run:
          npm run dev:server
      
      - name: Run test suits
        env:
          DATABASE_URL: postgresql://budgets:budgets@localhost:5432/budgets?schema=public
        run:
          npm run test:dev